name: Docker Image CI

on:
  push:
    branches: [ main,  ]
  pull_request:
    branches: [ main ]

jobs:
  bake:
    runs-on: ubuntu-latest
    steps:
    - id: dockerRepo
      uses: ASzc/change-string-case-action@v1
      with:
          string: "${{ github.repository }}"
    
    - name: Setup docker buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/bake-action@master
      with:
        push: true
