name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  bake:
    runs-on: ubuntu-latest
    steps:
    - id: dockerRepoName
      uses: ASzc/change-string-case-action@v1
      with:
          string: "${{ github.repository }}"
    
    - name: Setup docker buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Calculate next version
      uses: cezarypiatek/NextVersionGeneratorAction@0.4
      with:
        major-pattern: 'BREAKING CHANGES:'
        minor-pattern: 'FEATURE:'
        patch-pattern: '.*'
        output-to-env-variable: 'VersionPrefix'
    
    - name: print version
      run: echo "Build number is $VersionPrefix"
        
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ steps.dockerRepoName.outputs.lowercase }}
  
